feat(bin): add `ep` (Edit Pipe)

diff --git a/bin/bin/vt b/bin/bin/vt
--- a/bin/bin/vt
+++ b/bin/bin/vt
@@ -9,10 +9,10 @@ set -o pipefail
 COMMAND='let g:term_vt = 1 | terminal '"$@"
 
 if which nvim > /dev/null 2>&1; then
-  nvim -c "$COMMAND"
+    nvim -c "$COMMAND"
 elif which vim > /dev/null 2>&1; then
-  vim -c "$COMMAND"
+    vim -c "$COMMAND"
 else
-  echo "nvim/vim not found" 1>&2
-  exit 1
+    echo "nvim/vim not found" 1>&2
+    exit 1
 fi
